### ISSUE TITLE
На сайте в хранилище номера иногда начинаются не с 0, а с 2 или с 7.

### ISSUE THREAD

**Issue by meerstein** [meerstein/rbtm#28]
![image](https://cloud.githubusercontent.com/assets/5503603/9785804/b60a16fa-57bd-11e5-9c7d-5a76c670543b.png)

**Comment by buzmakov** [comment]
Сегодня обнаружил, что последний кадр стал первым
Т.е. нумерация идёт так 22, 1, 2, ... 21
http://xtomo.ru/storage/storage_record_1c418f87-8b7e-44b0-a7a7-47f4bedde298/

**Comment by meerstein** [comment]
В прошлом Вашем эксперименте, который уже удален, фреймы идут в странном порядке. Примерно так 1-600, 700-750, 601-699. 
Очевидно, где-то нужно добавить сортировку.

P.S. Проблема описанная в первом посте, уже давно не повторяется.
