### ISSUE TITLE
Add HTTPS for web

### ISSUE THREAD

**Issue by buzmakov** [meerstein/rbtm#31]
Можно получить бесплатный сертификат для сайта.

http://www.opennet.ru/opennews/art.shtml?num=43452

**Comment by meerstein** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=xtomo.ru&latest

**Comment by buzmakov** [comment]
Ура!

**Comment by buzmakov** [comment]
Нужно обновить сертификат и автоматизировать процедуру получения
